project:
  type: website

website:
  title: "2025 창의융합과제연구"
  navbar:
    left:
      - href: 2025 정보과제연구.ipynb
        text: Page1
      - href: 정보과제연구1.ipynb
        text: Page2


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



